// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0kDEVTxPKWbR-FrW8mSa6--Ft_TD2tp8',
    appId: '1:953336269887:web:f207c19cd1811ecf8cbc8a',
    messagingSenderId: '953336269887',
    projectId: 'nine-dart-score',
    authDomain: 'nine-dart-score.firebaseapp.com',
    storageBucket: 'nine-dart-score.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXjaTx9hINTZR553JR_r959Z0iSO7-K70',
    appId: '1:953336269887:android:b84c1cb522fbfb0a8cbc8a',
    messagingSenderId: '953336269887',
    projectId: 'nine-dart-score',
    storageBucket: 'nine-dart-score.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqAlceJLaZOwHIUTKyLM9JBjUqYOLEgyM',
    appId: '1:953336269887:ios:22facb3399a96dd18cbc8a',
    messagingSenderId: '953336269887',
    projectId: 'nine-dart-score',
    storageBucket: 'nine-dart-score.firebasestorage.app',
    iosBundleId: 'com.example.nineDartScore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqAlceJLaZOwHIUTKyLM9JBjUqYOLEgyM',
    appId: '1:953336269887:ios:22facb3399a96dd18cbc8a',
    messagingSenderId: '953336269887',
    projectId: 'nine-dart-score',
    storageBucket: 'nine-dart-score.firebasestorage.app',
    iosBundleId: 'com.example.nineDartScore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0kDEVTxPKWbR-FrW8mSa6--Ft_TD2tp8',
    appId: '1:953336269887:web:f8f9e54766b3718f8cbc8a',
    messagingSenderId: '953336269887',
    projectId: 'nine-dart-score',
    authDomain: 'nine-dart-score.firebaseapp.com',
    storageBucket: 'nine-dart-score.firebasestorage.app',
  );

}